pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Android-Modern-pl"
include ':app'
include ':core'
include ':data'
include ':features'
include ':design'
include ':network'
include ':business'
include ':business:analytics'
include ':business:analytics:impl'
include ':business:analytics:public'
